### ISSUE TITLE
Wrong authorized_keys access right.

### ISSUE THREAD

**Issue by pollyrobin** [unixtastic/git-ssh-server#5]
Minor thing with the guide. The guide works perfect.
Adding the following to the guide may fix some issues when people are following it: 
chmod +600 .ssh/authorized_keys

authorized_keys need 600 otherwise the key check might fail.
And what already is an [issue] ( #3 ) that the ssh server needs a start after making the container.

**Comment by unixtastic** [comment]
Thanks for letting me know. I added that chmod.

Let me know if you thing this issue is fixed so I can close it.

**Comment by pollyrobin** [comment]
Thanks! it works great
